name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - "**.mod"

env:
  KPM_REG: "xpkg.upbound.io"
  KPM_REPO: "upbound"
  UP_API_TOKEN: ${{ secrets.UP_E2E_API_TOKEN || secrets.UP_API_TOKEN }}
  UP_ROBOT_ID: ${{ secrets.UP_E2E_ROBOT_ID || secrets.UP_ROBOT_ID }}

jobs:
  publish_pkg:
    runs-on: ubuntu-latest
    name: Publish
    steps:

      - name: Install kcl
        run: wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Login
        if: env.UP_ROBOT_ID != '' && env.UP_API_TOKEN != ''
        run: kcl registry login -u ${{ env.UP_ROBOT_ID }} -p ${{ env.UP_API_TOKEN }} xpkg.upbound.io

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Publish to xpkg.upbound.io
        run: |
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q 'kcl.mod'; then
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              ./scripts/release.sh $file
            done
          fi
